// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMDNBF8ERAYx9gyyqY_sKYteQ_TvalISg',
    appId: '1:201825156875:web:a96434376d27266751ec0e',
    messagingSenderId: '201825156875',
    projectId: 'movie-app-using-firebase',
    authDomain: 'movie-app-using-firebase.firebaseapp.com',
    storageBucket: 'movie-app-using-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWgmD1nwsEKI9jrapFDz9C_gQp_A0ntY',
    appId: '1:201825156875:android:bb05f8b5dfb8708551ec0e',
    messagingSenderId: '201825156875',
    projectId: 'movie-app-using-firebase',
    storageBucket: 'movie-app-using-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGi8pqNuKFgWNc-jLaopMr1t3lpVRVzk',
    appId: '1:201825156875:ios:587d8d4ef5f1f2c151ec0e',
    messagingSenderId: '201825156875',
    projectId: 'movie-app-using-firebase',
    storageBucket: 'movie-app-using-firebase.appspot.com',
    iosClientId: '201825156875-u1se1n06a6i0l4ndvnmk1ab5ad6bkopo.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGi8pqNuKFgWNc-jLaopMr1t3lpVRVzk',
    appId: '1:201825156875:ios:587d8d4ef5f1f2c151ec0e',
    messagingSenderId: '201825156875',
    projectId: 'movie-app-using-firebase',
    storageBucket: 'movie-app-using-firebase.appspot.com',
    iosClientId: '201825156875-u1se1n06a6i0l4ndvnmk1ab5ad6bkopo.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieapp',
  );
}
